[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
sslCertFile = ".ssl/cert.pem"
sslKeyFile = ".ssl/key.pem"

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 